version: '2'

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: vapor_username
      POSTGRES_DB: vapor_database
      POSTGRES_PASSWORD: vapor_password
    ports:
      - 5432:5432
